### ISSUE TITLE
是否会考虑加入时区解析

### ISSUE THREAD

**Issue by xunyoyo** [suiyunonghen/datetime#2]
比如:
```moonbit
pub(all) struct DateTime {
  timestamp : Double  // 原有的时间戳
  timezone : Int      // 新增的时区字段，表示与 UTC 的偏移分钟数
}
```

解析时区信息：
在 parse_datetime 函数中，解析输入字符串中的时区信息，例如处理类似 "2024-12-03T12:32:33+08:00" 这样的格式。

如果有这样的想法，我可以编写一些功能的代码并pr。

**Comment by suiyunonghen** [comment]
> 比如:
> 
> ```moonbit
> pub(all) struct DateTime {
>   timestamp : Double  // 原有的时间戳
>   timezone : Int      // 新增的时区字段，表示与 UTC 的偏移分钟数
> }
> ```
> 
> 解析时区信息： 在 parse_datetime 函数中，解析输入字符串中的时区信息，例如处理类似 "2024-12-03T12:32:33+08:00" 这样的格式。
> 
> 如果有这样的想法，我可以编写一些功能的代码并pr。

非常欢迎来PR啊，是有想法折腾一个时区的，由于主要的目的是优先实现[msgpack编码解码库moonvalue](https://github.com/suiyunonghen/moonvalue)里面的时间扩展类型实现，这个要用，所以就先实现了一个很简单的，先把msgpack的走通。

**Comment by xunyoyo** [comment]
好的好的👌
